import { StyleSheet, Dimensions } from "react-native";

import { normalisera } from "./NormaliseraStorlek";
import colors from "../konfig/colors";

const windowBredd = Dimensions.get("window").width;

const styles = StyleSheet.create({
  betygsbar: {
    flexDirection: "row",
    width: "100%",
    aspectRatio: 375 / 68,
    backgroundColor: colors.bakgrund2,
    alignItems: "center",
    justifyContent: "center",
    // borderWidth: 1,
    // borderColor: colors.kant,
  },
  betygsknapp: {
    width: "16%",
    aspectRatio: 1 / 1,
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    margin: normalisera(15),
    borderRadius: "9999",
    borderWidth: 1,
    borderColor: colors.kant,
  },
  bildruta: {
    flexDirection: "vertical",
    width: normalisera(160),
    aspectRatio: 1 / 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: normalisera(7),
    marginTop: normalisera(14),
    backgroundColor: colors.bakgrund0,
    overflow: "hidden",
  },
  // bildtextbar: {
  //   flexDirection: "row",
  //   aspectRatio: 300 / 28,
  //   width: "100%",
  //   backgroundColor: colors.bakgrund3,
  //   alignItems: "center",
  //   justifyContent: "center",
  // },
  bottenyta: {
    flexDirection: "row",
    width: "100%",
    aspectRatio: 375 / 72,
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    // borderWidth: 1,
    // borderColor: colors.kant,
  },
  closeikonbox: {
    height: "60%",
    aspectRatio: 1 / 1,
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
  },
  contentruta: {
    flexDirection: "vertical",
    width: "80%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: normalisera(7),
    // borderWidth: 1,
    // borderColor: colors.kant,
  },
  contentrutanocolor: {
    flexDirection: "vertical",
    width: "94%",
    alignItems: "center",
    justifyContent: "center",
  },
  emptybar: {
    flexDirection: "row",
    width: "100%",
    aspectRatio: 375 / 14,
    backgroundColor: colors.bakgrund2,
  },
  // fixyta: {
  //   flex: 1,
  //   justifyContent: "center",
  //   alignItems: "center",
  //   backgroundColor: "red",
  // },
  flankruta: {
    flexDirection: "column",
    width: "14%",
    height: "100%",
    backgroundColor: colors.bakgrund2,
  },
  forumknapp2: {
    width: "16%",
    aspectRatio: 1 / 1,
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    margin: normalisera(15),
    borderRadius: "9999",
    borderWidth: 1,
    borderColor: colors.kant,
  },
  // forumknapp2klickad: {
  //   width: "16%",
  //   aspectRatio: 1 / 1,
  //   backgroundColor: colors.primary,
  //   alignItems: "center",
  //   justifyContent: "center",
  //   margin: normalisera(15),
  //   borderRadius: "9999",
  //   borderWidth: 1,
  //   borderColor: colors.kant,
  // },
  forummenyknapp: {
    flexDirection: "row",
    height: "100%",
    width: "90%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    margin: normalisera(15),
    borderRadius: normalisera(7),
    borderWidth: 1,
    borderColor: colors.kant,
  },
  forumyta2: {
    flexDirection: "row",
    height: "100%",
    width: "100%",
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: normalisera(7),
    borderWidth: 1,
    borderColor: colors.kant,
  },
  forumyta2klickad: {
    flexDirection: "row",
    height: "100%",
    width: "100%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: normalisera(7),
    borderWidth: 1,
    borderColor: colors.kant,
  },
  ikonbox: {
    flexDirection: "column",
    width: "100%",
    aspectRatio: 1 / 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: colors.bakgrund2,
  },
  image: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.kant,
    borderRadius: normalisera(7),
    resizeMode: "contain",
  },
  infotextbar: {
    flexDirection: "row",
    aspectRatio: 375 / 21,
    width: "100%",
    backgroundColor: colors.bakgrund2,
    alignItems: "center",
    justifyContent: "center",
  },
  klickadbetygsknapp: {
    flexDirection: "row",
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    borderRadius: 9999,
  },
  klickadbottenyta: {
    flexDirection: "row",
    width: "100%",
    height: "100%",
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.6,
    borderWidth: 1,
    borderColor: colors.kant,
  },
  klickadcontentruta: {
    flexDirection: "vertical",
    width: "100%",
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.6,
    borderRadius: normalisera(7),
    borderWidth: 1,
    borderColor: colors.kant,
  },
  klickadforummenyknapp: {
    flexDirection: "row",
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    opacity: 0.6,
    borderRadius: normalisera(7),
  },
  klickadknapp: {
    flexDirection: "row",
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    opacity: 0.6,
    borderRadius: normalisera(7),
  },
  KlickadListItemKnapp: {
    flexDirection: "row",
    height: "100%",
    width: "80%",
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    margin: normalisera(15),
    borderRadius: normalisera(7),
    borderWidth: 1,
    borderColor: colors.kant,
    opacity: 0.6,
  },
  klickadpresidentknapp: {
    width: "100%",
    height: "100%",
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    margin: 0,
    opacity: 0.6,
    borderTopRightRadius: normalisera(7),
    borderBottomRightRadius: normalisera(7),
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.kant,
  },
  klickadstatementknapp: {
    width: "100%",
    height: "100%",
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    margin: 0,
    borderTopLeftRadius: normalisera(7),
    borderBottomLeftRadius: normalisera(7),
    opacity: 0.6,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.kant,
  },
  klickadtoppknapp2: {
    flexDirection: "row",
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    opacity: 0.6,
    borderRadius: normalisera(7),
  },
  klickbetygsknapp: {
    flexDirection: "row",
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.bakgrund3,
    borderRadius: 9999,
  },
  klickbottenyta: {
    flexDirection: "row",
    width: "100%",
    height: "100%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.kant,
  },
  klickcontentruta: {
    flexDirection: "vertical",
    width: "100%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: normalisera(7),
    borderWidth: 1,
    borderColor: colors.kant,
  },

  klickforummenyknapp: {
    flexDirection: "row",
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.bakgrund3,
    borderRadius: normalisera(7),
  },
  klickknapp: {
    flexDirection: "row",
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.bakgrund3,
    borderRadius: normalisera(7),
  },
  KlickListItemKnapp: {
    flexDirection: "row",
    height: "100%",
    width: "80%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    margin: normalisera(15),
    borderRadius: normalisera(7),
    borderWidth: 1,
    borderColor: colors.kant,
  },
  klickpresidentknapp: {
    width: "100%",
    height: "100%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    margin: 0,
    borderTopRightRadius: normalisera(7),
    borderBottomRightRadius: normalisera(7),
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.kant,
  },
  klickstatementknapp: {
    width: "100%",
    height: "100%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    margin: 0,
    borderTopLeftRadius: normalisera(7),
    borderBottomLeftRadius: normalisera(7),
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.kant,
  },
  klicktoppknapp2: {
    flexDirection: "row",
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.bakgrund3,
    borderRadius: normalisera(7),
  },

  kompensationsknapp2: {
    width: "15%",
    aspectRatio: 1 / 1,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    margin: normalisera(15),
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: colors.primary,
    opacity: 0,
  },
  kompensationsknapp2klickad: {
    width: "15%",
    aspectRatio: 1 / 1,
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    margin: normalisera(15),
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: colors.bakgrund3,
  },
  leftknapp: {
    flexDirection: "row",
    height: "100%",
    width: "31%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    margin: normalisera(15),
    borderRadius: normalisera(7),
    borderWidth: 1,
    borderColor: colors.kant,
  },
  listItem: {
    flexDirection: "row",
  },
  listItemBar: {
    flexDirection: "row",
    width: "100%",
    aspectRatio: 375 / 35,
    backgroundColor: colors.bakgrund2,
    alignItems: "center",
    justifyContent: "center",
  },

  mittknapp: {
    height: "100%",
    width: "31%",
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    margin: normalisera(15),
    borderRadius: normalisera(7),
    borderWidth: 1,
    borderColor: colors.kant,
  },
  mittruta: {
    flexDirection: "row",
    width: "72%",
    height: "100%",
    justifyContent: "center",
    alignItems: "flex-start",
    backgroundColor: "colors.bakgrund2",
  },
  paddinguppe: {
    flexDirection: "row",
    width: "100%",
    aspectRatio: 375 / 21,
    backgroundColor: colors.bakgrund2,
  },
  paddingnere: {
    flexDirection: "row",
    width: "100%",
    aspectRatio: 375 / 70,
    backgroundColor: colors.bakgrund2,
  },
  poolfinnarbar: {
    flexDirection: "row",
    width: "100%",
    aspectRatio: 375 / 35,
    backgroundColor: colors.bakgrund2,
    alignItems: "center",
    justifyContent: "center",
  },
  presidentknappAkt: {
    width: "32%",
    height: "100%",
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    margin: 0,
    borderTopRightRadius: normalisera(7),
    borderBottomRightRadius: normalisera(7),
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.kant,
  },
  presidentknappPass: {
    width: "32%",
    height: "100%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    margin: 0,
    borderTopRightRadius: normalisera(7),
    borderBottomRightRadius: normalisera(7),
  },
  reportpresstatbar: {
    flexDirection: "row",
    width: "100%",
    aspectRatio: 375 / 35,
    backgroundColor: colors.bakgrund2,
    alignItems: "center",
    justifyContent: "center",
  },
  reportpresstatknapp: {
    width: "20%",
    height: "100%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    margin: normalisera(15),
    borderRadius: "6%",
    borderWidth: 1,
    borderColor: colors.kant,
  },
  rightknapp: {
    flexDirection: "row",
    height: "100%",
    width: "31%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    margin: normalisera(15),
    borderRadius: normalisera(7),
    borderWidth: 1,
    borderColor: colors.kant,
  },
  rotationsyta: {
    width: windowBredd,
    height: "100%",
    backgroundColor: colors.bakgrund2,
    justifyContent: "top",
  },
  rubrikbar: {
    flexDirection: "row",
    aspectRatio: 300 / 28,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: normalisera(7),
  },
  // rubrikff: {
  //   fontSize: normalisera(17),
  //   fontStyle: "normal",
  //   fontWeight: "600",
  //   color: colors.rubrikff,
  //   fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
  // },
  safeyta: {
    flex: 1,
    backgroundColor: colors.bakgrund0,
    justifyContent: "top",
    alignItems: "center",
  },
  scrollyta: {
    justifyContent: "top",
    alignItems: "center",
    backgroundColor: colors.bakgrund2,
  },
  sidfinnarbar: {
    flexDirection: "row",
    width: "100%",
    aspectRatio: 375 / 35,
    backgroundColor: colors.bakgrund2,
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  statementknappAkt: {
    width: "32%",
    height: "100%",
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    margin: 0,
    borderTopLeftRadius: normalisera(7),
    borderBottomLeftRadius: normalisera(7),
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.kant,
  },
  statementknappPass: {
    width: "32%",
    height: "100%",
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    margin: 0,
    borderTopLeftRadius: normalisera(7),
    borderBottomLeftRadius: normalisera(7),
    // borderTopWidth: 1,
    // borderLeftWidth: 1,
    // borderBottomWidth: 1,
    // borderColor: colors.kant,
  },

  // textff: {
  //   fontSize: normalisera(12),
  //   fontStyle: "normal",
  //   fontWeight: "400",
  //   color: colors.textff,
  //   fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
  // },
  textruta: {
    flexDirection: "row",
    width: "90%",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: normalisera(7),
  },
  textrutaCol: {
    flexDirection: "column",
    width: "90%",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: normalisera(7),
  },
  toppknapp2: {
    height: "80%",
    aspectRatio: 1 / 1,
    backgroundColor: colors.bakgrund3,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.kant,
    borderRadius: normalisera(7),
  },
  toppLista: {
    alignItems: "center",
  },
  toppruta: {
    flexDirection: "row",
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "flex-start",
    backgroundColor: colors.bakgrund2,
  },
  // toppListeYta: {
  //   width: "100%",
  //   height: "100%",
  //   // backgroundColor: colors.bakgrund2,
  //   backgroundColor: "green",
  //   alignItems: "center",
  //   justifyContent: "center",
  // },
  toppyta: {
    flexDirection: "row",
    width: "100%",
    aspectRatio: 375 / 72,
    backgroundColor: colors.bakgrund2,
    justifyContent: "center",
  },
  totalyta: {
    flex: 1,
    backgroundColor: colors.bakgrund0,
    justifyContent: "top",
    alignItems: "center",
  },
  visanuyta: {
    flexDirection: "row",
    height: "100%",
    width: "100%",
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.kant,
  },
});

export default styles;
